import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ჩვენს შესახებ | Soulart - About Us | Soulart",
  description:
    "გაიგე Soulart.ge-ს შესახებ - ქართული ონლაინ პლატფორმა ხელოვანებისა და ხელნაკეთი ნივთების მოყვარულებისთვის. ჩვენი ისტორია, მისია და ხედვა. Learn about Soulart.ge - a Georgian online platform for artists and art lovers.",
  keywords: [
    "ჩვენს შესახებ",
    "ნახატები",
    "ქართველი მხატვრების ნახატები",
    "საჩუქრები",
    "საჩუქრად ნახატები",
    "საჩუქრად ხელნაკეთი ნივთები",
    "ნახატიები ონლაინ",
    "ხელნაკეთი ნივთები ონლაინ",
    "ქართველი მხატვრები",
    "ქართული ხელოვნება",
    "ნახატი",
    "ხელნაკეთი",
    "ნახატების საიტი",
    "ხელნაკეთი ნივთების საიტი",
    "ნახატების მაღაზია",
    "ხელნაკეთი ნივთების მაღაზია",
    "ხელოვანები",
    "ქართული ხელოვნება ონლაინ",
    "ქართველი მხატვრები",
    "ნახატების ვებგვერდი",
    "ხელნაკეთი ნივთების ვებგვერდი",
    "ყველა ქართველი მხატვრის ნახატები",
    "ყველა ქართველი ხელოვანის ხელნაკეთი ნივთები",
    "ქართველი მხატვრების ნამუშევრები",
    "ქართველი ხელოვანების ნამუშევრები",
    "Soulart ბლოგი",
    "Soulart ინტერვიუები",
    "Soulart ქართველი მხატვრები",
    "ხელოვანები",
    "Soulart.ge",
    "ხელნაკეთი ნივთები",
    "იყიდება ნახატები",
    "იყიდება ხელნაკეთი ნივთები",
    "ხელოვნების პლატფორმა",
    "ხელოვანების მხარდაჭერა",
    "Soulart ისტორია",
    "ქართული პლატფორმა",
    "ხელოვანებისთვის",
    "ხელნაკეთი ნივთები",
    "ფასდაკლებები",
    "ხელოვნების ბაზარი",
    "ნახატების კოლექცია",
    "ხელოვნების გალერეა",
    "ხელოვანების საზოგადოება",
    "იყიდება ხელოვნების ნიმუშები",
    "ხელოვნების ღონისძიებები",
    "ხელოვნების გამოფენები",
    "ჩვენი ისტორია",
    "იყიდება ნახატები ონლაინ",
    "იყიდება ხელნაკეთი ნივთები ონლაინ",
    "ხელოვნების პლატფორმა საქართველოში",
    "ხელოვანების მხარდაჭერა ონლაინ",
    "Soulart ისტორია",
    "დამფუძნებლები",
    "მისია",
    "ხედვა",
    "ლევან ბეროშვილი",
    "ანი ბეროშვილი",
    "about us",
    "our story",
    "mission",
    "vision",
    "handmade items",
    "Georgian art",
    "Georgian artists",
    "paintings for sale",
    "handmade for sale",
    "art marketplace",
    "art community",
    "buy art online",
    "buy handmade online",
    "art platform",
    "support artists",
    "Soulart history",
    "paintings for sale",
    "handmade for sale",
    "Georgian platform",
    "handmade",
    "artists platform",
    "Soulart founders",
    "Levan Beroshvili",
    "Ani Beroshvili",
    "Microsoft",
    "software engineer",
    "პროგრამული ინჟინერი",
  ],
  openGraph: {
    title: "ჩვენს შესახებ | Soulart - About Us",
    description:
      "გაიგე Soulart.ge-ს შესახებ - ქართული ონლაინ პლატფორმა ხელოვანებისა და ხელნაკეთი ნივთების მოყვარულებისთვის. ჩვენი ისტორია, დამფუძნებლები , მისია და ხედვა.",
    type: "website",
    url: "https://soulart.ge/about",
    siteName: "Soulart",
    locale: "ka_GE",
    alternateLocale: ["en_US"],
    images: [
      {
        url: "https://soulart.ge/van-gogh.jpg",
        width: 1200,
        height: 630,
        alt: "Soulart - ქართული პლატფორმა ხელოვანებისთვის",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@soulart_ge",
    title: "ჩვენს შესახებ | Soulart - About Us",
    description:
      "გაიგე Soulart.ge-ს შესახებ - ქართული ონლაინ პლატფორმა ხელოვანებისა და ხელნაკეთი ნივთების მოყვარულებისთვის.",
    images: ["https://soulart.ge/van-gogh.jpg"],
  },
  alternates: {
    canonical: "https://soulart.ge/about",
    languages: {
      "ka-GE": "https://soulart.ge/about",
      "en-US": "https://soulart.ge/about",
    },
  },
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
