import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/__tests__/setup.tsx'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'lcov'],
      include: ['src/hooks/**', 'src/lib/**'],
      exclude: [
        'src/**/*.test.*',
        'src/**/*.spec.*',
        'src/__tests__/**',
        'src/**/*.d.ts',
        'src/lib/open-ai.ts',
        'src/lib/stripe.ts',
        'src/lib/axios.ts',
        'src/lib/fetch-with-auth.ts',
        'src/lib/fetch-with-auth-cookies.ts',
        'src/lib/artist-api.ts',
        'src/lib/banner-api.ts',
        'src/lib/chat-api.ts',
        'src/lib/auth-cookies.ts',
        'src/lib/cloudflare-cleanup.ts',
        'src/lib/gallery-interaction.service.ts',
        'src/lib/use-shipping-rates.ts',
        'src/hooks/useAuth.ts',
        'src/hooks/useStocks.ts',
        'src/hooks/useUsdRate.ts',
        'src/hooks/useGeoLocation.ts',
        'src/hooks/useLocalizedRouter.ts',
        'src/hooks/useOptimizations.ts',
        'src/hooks/useVersionPolling.ts',
        'src/hooks/useCacheStatus.ts',
        'src/hooks/useInteractions.ts',
        'src/hooks/useVisitorTracking.ts',
        'src/hooks/ThemeContext.tsx',
        'src/hooks/analytics-store.ts',
        'src/hooks/use-analytics.ts',
        'src/hooks/use-auth-cookies.ts',
        'src/hooks/use-auth.ts',
        'src/hooks/use-error-handler.ts',
        'src/hooks/use-referral-pricing.ts',
        'src/hooks/use-canvas-tracking.ts',
        'src/hooks/use-scroll-to-bottom.tsx',
        'src/hooks/useVersionPolling.ts',
        'src/hooks/use-analytics-store.ts',
        'src/hooks/use-sales-tracking.ts',
        'src/hooks/useAuctionPolling.ts',
        'src/hooks/useGalleryInteractions.ts',
        'src/hooks/usePerformanceOptimizations.ts',
        'src/lib/seo-keywords.ts',
        'src/lib/ga4-analytics.ts',
        'src/lib/pwa-link-handler.ts',
      ],
      thresholds: {
        statements: 80,
        branches: 70,
        functions: 80,
        lines: 80,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
